baseURL = 'https://jinshoji3.github.io/'
languageCode = 'ja-jp'
title = "Shoji's Research Notes"
theme = 'PaperMod'

[params]
  [params.profileMode]
    enabled = true
    title = "SHOJI"
    subtitle = "備忘録since2026"
    imageUrl = "prof_ramen.png"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "My Avatar"

  [[params.profileMode.buttons]]
    name = "備忘録"
    url = "/categories/備忘録/"

  [[params.profileMode.buttons]]
    name = "読書記録"
    url = "/categories/読書記録/"

  [[params.profileMode.buttons]]
    name = "すべての記事"
    url = "/posts/"